services:
  - type: web
    name: skillverse-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        fromBuild: true
      - key: FIREBASE_PRIVATE_KEY
        fromBuild: true
      - key: FIREBASE_CLIENT_EMAIL
        fromBuild: true
      - key: FIREBASE_PROJECT_ID
        fromBuild: true
      - key: STRIPE_SECRET_KEY
        fromBuild: true
      - key: STRIPE_WEBHOOK_SECRET
        fromBuild: true
      - key: FRONTEND_URL
        fromBuild: true

  - type: web
    name: skillverse-frontend
    env: node
    region: oregon
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        value: https://skillverse-backend.onrender.com/api
      - key: NODE_ENV
        value: production
